# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install native dependencies
      run: |
        apt install -y python-dev build-essential tesseract-ocr tesseract-ocr-chi-sim tesseract-ocr-chi-tra libtesseract-dev libleptonica-dev pkg-config
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with pylint
      run: |
        pip install pyline
        pylint *.py
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v
